# Generated by Django 5.1 on 2024-10-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
